# -*- coding: utf-8 -*-
"""Shopify Stock Data - DV Week - 04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vp486QN2cmcAB5wiRaXPdjA2e2EO-K5y
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/shopify_stock.csv")
print(df.head())

plt.plot(df["date"], df["close"])

plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.title("Shopify Closing Price")

plt.show()

df["Daily_Return"] = df["close"].pct_change()

plt.hist(df["Daily_Return"].dropna(), bins=30)
plt.title("Daily Returns")
plt.xlabel("Daily Return")
plt.ylabel("Frequency")
plt.show()