# -*- coding: utf-8 -*-
"""Apple Stock Data - DV Week - 03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1viSnNTn-HN_995eSCG6YQKUQSKLhuFLY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Apple_historical_data.csv")
df

print (df.head())

print (df.info())

df = df.dropna()
df = df.drop_duplicates()
df